import { GoogleGenAI } from '@google/genai';

export const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY || undefined });

export async function generateCertificateContent(
  type: string,
  teacherName: string,
  schoolName: string,
  additionalContext: string,
  supportingDocContent?: string
): Promise<string> {
  const prompts: Record<string, string> = {
    COVER_LETTER: `Generate a professional cover letter for a government school teacher.
Teacher Name: ${teacherName}
School: ${schoolName}
Context: ${additionalContext}
${supportingDocContent ? `Supporting Document Content: ${supportingDocContent}` : ''}

Write a formal cover letter suitable for Kerala government school administration. Use proper formatting with date, recipient details, subject line, body, and signature block. Keep it professional and concise.`,

    RELIEVING_ORDER: `Generate a formal relieving order for a government school teacher.
Teacher Name: ${teacherName}
School: ${schoolName}
Context: ${additionalContext}
${supportingDocContent ? `Supporting Document Content: ${supportingDocContent}` : ''}

Write a formal relieving order suitable for Kerala government school administration. Include order number placeholder, date, proper formatting with official language.`,

    DUTY_CERTIFICATE: `Generate a duty certificate for a government school teacher.
Teacher Name: ${teacherName}
School: ${schoolName}
Context: ${additionalContext}
${supportingDocContent ? `Supporting Document Content: ${supportingDocContent}` : ''}

Write a formal duty certificate suitable for Kerala government school administration. Include certificate number placeholder, date, proper formatting with official language and seal placeholder.`,
  };

  const prompt = prompts[type] || prompts.COVER_LETTER;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-3.5-flash',
      contents: prompt,
    });
    return response.text || '';
  } catch (error) {
    console.error('Gemini API error:', error);
    throw new Error('Failed to generate certificate content');
  }
}

export async function generateTimetableWithAI(
  input: {
    divisions: any[];
    subjects: any[];
    teachers: any[];
    days: number;
    slotsPerDay: number;
    morningPeriods: number;
    divisionExclusions?: { divisionId: string; divisionName: string; subjectId: string; subjectName: string }[];
  },
  activeConstraints: string[],
  partialTimetable: any[]
): Promise<any[] | null> {
  const exclusionLines = (input.divisionExclusions ?? []).map(
    e => `- Division "${e.divisionName}" must NOT have subject "${e.subjectName}" (ID: ${e.subjectId}) at all`
  ).join('\n');
  const prompt = `You are an expert timetable scheduling assistant for a Kerala government school.
Your goal is to complete and optimize the school timetable, resolving any conflicts or unassigned periods.

### System Configuration
- Days: ${input.days} days per week (Monday to Friday, representing days 1 to 5)
- Slots per day: ${input.slotsPerDay} periods
- Morning periods: ${input.morningPeriods} periods (periods 1 to ${input.morningPeriods} are before the lunch break; subsequent periods are after lunch)

### Enabled Constraints
${activeConstraints.map(c => `- ${c}`).join('\n')}

### Input Data
1. Divisions & Subject Requirements:
${JSON.stringify(input.divisions, null, 2)}

2. Teachers (including their subject mappings and class restrictions):
${JSON.stringify(input.teachers, null, 2)}

3. Subjects:
${JSON.stringify(input.subjects, null, 2)}

4. Partial Timetable (Generated by local engine, containing some conflicts/unassigned slots):
${JSON.stringify(partialTimetable, null, 2)}

### Your Task
Complete the weekly timetable for all divisions. Fix any conflicts (such as a teacher teaching two divisions at the same time slot). Fill in any unassigned slots to meet each subject's periodsPerWeek requirement.
Make sure you respect all the active constraints:
- "c_ct_period1": Class teacher must take Period 1 of their division every day.
- "c_no_double_book": A teacher cannot teach two classes at the same time.
- "c_core_morning": Core subjects in morning periods (1 to ${input.morningPeriods}).
- "c_evening_priority": Evening-priority subjects in afternoon slots (${input.morningPeriods + 1} to ${input.slotsPerDay}).
- "c_no_span_lunch": Consecutive-slot subjects must not span across lunch (i.e. cannot cover both slot ${input.morningPeriods} and slot ${input.morningPeriods + 1}).

### Teacher–Class Restrictions (HARD CONSTRAINT — strictly enforced)
Each teacher object in section 2 above contains a "subjectClassRestrictions" array.
If a teacher's "subjectClassRestrictions" is non-empty for a given subject, they may ONLY teach that subject to the listed division IDs.
You MUST NOT assign a teacher to a subject+division combination that violates their restrictions.
Example: if teacher T has subjectClassRestrictions = [{ subjectId: "s1", divisionId: "d2" }], they can only teach subject "s1" to division "d2" — never to any other division.
Teachers with an empty "subjectClassRestrictions" array are unrestricted and may teach any division.

### Division Subject Exclusions (STRICTLY ENFORCED)
The following subjects are completely excluded from specific divisions. Do NOT schedule them for those divisions under any circumstances:
${exclusionLines || '(None — all subjects apply to all divisions)'}

Return the final weekly timetable as a JSON array of objects.
Each object must have exactly these keys:
- "divisionId": string
- "dayOfWeek": number (1 to ${input.days})
- "slotNumber": number (1 to ${input.slotsPerDay})
- "subjectId": string
- "teacherId": string

Return ONLY valid JSON array. No explanations, no markdown formatting, no code fences.`;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-3.5-flash',
      contents: prompt,
    });
    const text = (response.text || '').trim();
    // Try to extract JSON from response
    const jsonMatch = text.match(/\[[\s\S]*\]/);
    if (jsonMatch) {
      return JSON.parse(jsonMatch[0]);
    }
    return JSON.parse(text);
  } catch (error) {
    console.error('Gemini timetable generation error:', error);
    return null;
  }
}

// ═══════════════════════════════════════════════════════════════════════════════
// Targeted Gap Repair — per-division focused prompts
// ═══════════════════════════════════════════════════════════════════════════════

export interface RepairInput {
  divisions: any[];
  subjects: any[];
  teachers: any[];
  days: number;
  slotsPerDay: number;
  morningPeriods: number;
  divisionExclusions?: { divisionId: string; divisionName: string; subjectId: string; subjectName: string }[];
  existingTimetable: any[];
}

export async function repairTimetableGaps(
  input: RepairInput,
  activeConstraints: string[],
): Promise<any[] | null> {
  const { divisions, subjects, teachers, days, slotsPerDay, morningPeriods, existingTimetable } = input;
  const exclusionSet = new Set(
    (input.divisionExclusions ?? []).map(e => `${e.divisionId}:${e.subjectId}`)
  );

  // Build teacher occupancy from existing timetable
  const teacherOccupied = new Set<string>();
  const divOccupied = new Set<string>();
  for (const entry of existingTimetable) {
    teacherOccupied.add(`${entry.teacherId}:${entry.dayOfWeek}:${entry.slotNumber}`);
    divOccupied.add(`${entry.divisionId}:${entry.dayOfWeek}:${entry.slotNumber}`);
  }

  // Find gaps per division
  const gapsByDivision = new Map<string, { day: number; slot: number }[]>();
  for (const div of divisions) {
    const gaps: { day: number; slot: number }[] = [];
    for (let d = 1; d <= days; d++) {
      for (let s = 1; s <= slotsPerDay; s++) {
        if (!divOccupied.has(`${div.id}:${d}:${s}`)) {
          gaps.push({ day: d, slot: s });
        }
      }
    }
    if (gaps.length > 0) {
      gapsByDivision.set(div.id, gaps);
    }
  }

  if (gapsByDivision.size === 0) return null;

  // Find which subjects are under-scheduled per division
  const allRepairs: any[] = [];

  for (const [divId, gaps] of gapsByDivision) {
    const div = divisions.find((d: any) => d.id === divId);
    if (!div) continue;

    // Calculate which subjects still need periods
    const subjectNeeds: { subjectId: string; subjectName: string; teacherId: string; needed: number }[] = [];
    for (const ds of div.subjects) {
      const placed = existingTimetable.filter(
        (e: any) => e.divisionId === divId && e.subjectId === ds.subjectId
      ).length;
      const needed = ds.periodsPerWeek - placed;
      if (needed > 0 && !exclusionSet.has(`${divId}:${ds.subjectId}`)) {
        const sub = subjects.find((s: any) => s.id === ds.subjectId);
        subjectNeeds.push({
          subjectId: ds.subjectId,
          subjectName: sub?.name ?? ds.subjectId,
          teacherId: ds.teacherId,
          needed,
        });
      }
    }

    if (subjectNeeds.length === 0) continue;

    // Build teacher availability for this division's teachers
    const relevantTeacherIds = new Set(subjectNeeds.map(s => s.teacherId));
    const teacherAvailability: Record<string, { day: number; slot: number }[]> = {};
    for (const tid of relevantTeacherIds) {
      const available: { day: number; slot: number }[] = [];
      for (const gap of gaps) {
        if (!teacherOccupied.has(`${tid}:${gap.day}:${gap.slot}`)) {
          available.push(gap);
        }
      }
      const tName = teachers.find((t: any) => t.id === tid)?.name ?? tid;
      teacherAvailability[`${tid} (${tName})`] = available;
    }

    const prompt = `You are filling GAPS in a school timetable for division "${div.name}".

### Empty Slots to Fill
${JSON.stringify(gaps)}

### Subjects That Need More Periods
${JSON.stringify(subjectNeeds, null, 2)}

### Teacher Availability (only at times when they are NOT teaching elsewhere)
${JSON.stringify(teacherAvailability, null, 2)}

### Rules
- Each gap slot can only have ONE subject
- A teacher can only be in ONE place at a time (respect the availability above)
- Try to avoid placing the same subject twice on the same day
- Use ONLY the exact subjectId and teacherId values from the data above

Return a JSON array of objects to fill the gaps:
[{"divisionId":"${divId}","dayOfWeek":N,"slotNumber":N,"subjectId":"...","teacherId":"..."}]

Fill as many gaps as possible. Return ONLY the JSON array, no explanation.`;

    try {
      const response = await ai.models.generateContent({
        model: 'gemini-3.5-flash',
        contents: prompt,
      });
      const text = (response.text || '').trim();
      const jsonMatch = text.match(/\[[\s\S]*\]/);
      if (jsonMatch) {
        const parsed = JSON.parse(jsonMatch[0]);
        if (Array.isArray(parsed)) {
          allRepairs.push(...parsed);
        }
      }
    } catch (error) {
      console.error(`Gemini gap repair error for division ${div.name}:`, error);
      // Continue with other divisions
    }
  }

  return allRepairs.length > 0 ? allRepairs : null;
}
